### ISSUE TITLE
Milestone1 Checklist

### ISSUE THREAD

**Issue by dy-lin** [stat545ubc-2020/template-collaborative-milestone1#6]
- [ ] Teamwork Contract (5 pts total)
  - Address **3 out of 4** topics below:
    - [ ] Communication: (1 pt)
        - [ ] How will you communicate with each other? 
        - [ ] Will you have different mediums for different purposes?
        - [ ] How long will it realistically take you to respond to a message?
    - [ ] Submission: (1 pt)
      - [ ] Who will make the final submission for each milestone?
      - [ ] When will the final submission for each milestone be made?
    - [ ] Pull Requests: (1 pt)
      - [ ] If a pull request is to be made as part of a milestone, by when will it be made? 
      - [ ] And, how long will other teammates have to review that pull request?
    - [ ] Workflow: (1 pt)
        - [ ] will each teammate complete separate portions of the worksheet?
        - [ ] Or will you work together on multiple sections?
  - Thoughtfulness and clarity (2 pts)
- [ ] README (5 pts total)
  - [ ] Make a new document _in the root of your repository_ called `README.md`
  - Address **all three** topics below:
    - [ ] What is this project? (1 pt)
    - [ ] What files are in the project folder / GitHub repository? (1 pt)
    - [ ] How can they run code that appears in your folder / GitHub repository? (1 pt)
  - Thoughtfulness and clarity (2 pts)
