### ISSUE TITLE
Milestone 3 Checklist

### ISSUE THREAD

**Issue by dy-lin** [stat545ubc-2020/template-collaborative-milestone1#9]
# STAT 545A Collaborative Project: Milestone 2 Checklist (30 points)

## Troubleshooting document (1.5pts x 10 errors = 15pts)

+ [ ] Error 1
+ [ ] Error 2
+ [ ] Error 3
+ [ ] Error 4
+ [ ] Error 5
+ [ ] Error 6
+ [ ] Error 7
+ [ ] Error 8
+ [ ] Error 9
+ [ ] Error 10

## Pull requests (2.5pts x 4 PRs = 10pts)

+ Remember that *each student* must open at least **2 pull requests**. Therefore, **4** pull requests in total will be graded.

+ [ ] Pull Request 1: Student A creates a pull request and explains their work
    + [ ] Student B comments on the pull request, holding a discussion and implementing any additional fixes if needed
    + [ ] Either student merges and closes the pull request

+ [ ] Pull Request 2: Student B creates a pull request and explains their work
    + [ ] Student A comments on the pull request, holding a discussion and implementing any additional fixes if needed
    + [ ] Either student merges and closes the pull request

+ [ ] Pull Request 3: Student A creates a pull request and explains their work
    + [ ] Student B comments on the pull request, holding a discussion and implementing any additional fixes if needed
    + [ ] Either student merges and closes the pull request

+ [ ] Pull Request 4: Student B creates a pull request and explains their work
    + [ ] Student A comments on the pull request, holding a discussion and implementing any additional fixes if needed
    + [ ] Either student merges and closes the pull request

## Repo organization (1.25 x 4 = 5 points)

+ [ ] README.md
  + Must be in the **root** of your repository.
  + Instructions for creating your README were detailed in the [Milestone 1 instructions](https://stat545.stat.ubc.ca/collaborative-project/milestone1/readme/), under "README file".
  + If there is anything that needs to be fixed in your README, it would be detailed in the Milestone 1 feedback provided by a TA in an Issue in your repo.

+ [ ] Organization
  + [ ] No files should be duplicated (for example, if you have a TB2.Rmd in your "Milestone 2" subfolder, and another TB2.Rmd in the root of your repo, the latter should be deleted).
  + [ ] Files should be organized in subfolders, by Milestone. Therefore, your repo should contain:
    + [ ] A README.md file in the root of your repo
    + [ ] A teamwork document in the root of your repo
    + [ ] Milestone 1 subfolder
    + [ ] Milestone 2 subfolder
    + [ ] Milestone 3 subfolder

+ [ ] All pull requests should be resolved and closed
+ [ ] All issues should be resolved and closed
